### ISSUE TITLE
md5 check for `.parquet` files

### ISSUE THREAD

**Issue by vtddggg** [rom1504/cah-prepro#14]
Can you report the md5 value for 32 `.parquet` files?
To verify that all meta data is downloaded successfully.

**Comment by vtddggg** [comment]
After download all `.parquet` files, I can successfully read them by `pandas.read_parquet` except for `part-00000-5b54c5d5-bbcf-484d-a2ce-0d6f73df1a36-c000.snappy.parquet`.

I got following error when read the part 0:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mxf164419/anaconda3/lib/python3.7/site-packages/pandas/io/parquet.py", line 282, in read_parquet
    return impl.read(path, columns=columns, **kwargs)
  File "/home/mxf164419/anaconda3/lib/python3.7/site-packages/pandas/io/parquet.py", line 129, in read
    **kwargs).to_pandas()
  File "/home/mxf164419/anaconda3/lib/python3.7/site-packages/pyarrow/parquet.py", line 1942, in read_table
    use_pandas_metadata=use_pandas_metadata)
  File "/home/mxf164419/anaconda3/lib/python3.7/site-packages/pyarrow/parquet.py", line 1778, in read
    use_threads=use_threads
  File "pyarrow/_dataset.pyx", line 491, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3235, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: Couldn't deserialize thrift: TProtocolException: Invalid data
Deserializing page header failed.
```

So is this caused by the download is not completed for `part-00000-5b54c5d5-bbcf-484d-a2ce-0d6f73df1a36-c000.snappy.parquet` ?

**Comment by rom1504** [comment]
hi, yes it seems so, can you try redownloading it ? (from https://the-eye.eu/public/AI/cah/laion400m-met-release/laion400m-meta/)
I will provide the md5 hashes

**Comment by vtddggg** [comment]
I found the problem. 

It looks part-00000 downloaded by `aria2c "https://the-eye.eu/public/AI/cah/laion400m-met-release.torrent"` is broken, whose `md5` is `320421f8bd86c21b9f41fe6113415ca0`.

But part-00000 downloaded from https://the-eye.eu/public/AI/cah/laion400m-met-release/laion400m-meta/ has a different `md5` value (`f40c8e0c2203c3abfef1e7c0df21a83a`). It can be read by `pandas.read_parquet` successfully.

Maybe the right way is using https://the-eye.eu/public/AI/cah/laion400m-met-release/laion400m-meta/ for downloading.

**Comment by rom1504** [comment]
ok that is unexpected, the torrent and http ways should result in the same file
I will check what's going on
